// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XVIP1_M_H
#define XVIP1_M_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xvip1_m_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XVip1_m_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XVip1_m;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XVip1_m_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XVip1_m_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XVip1_m_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XVip1_m_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XVip1_m_Initialize(XVip1_m *InstancePtr, u16 DeviceId);
XVip1_m_Config* XVip1_m_LookupConfig(u16 DeviceId);
int XVip1_m_CfgInitialize(XVip1_m *InstancePtr, XVip1_m_Config *ConfigPtr);
#else
int XVip1_m_Initialize(XVip1_m *InstancePtr, const char* InstanceName);
int XVip1_m_Release(XVip1_m *InstancePtr);
#endif

void XVip1_m_Start(XVip1_m *InstancePtr);
u32 XVip1_m_IsDone(XVip1_m *InstancePtr);
u32 XVip1_m_IsIdle(XVip1_m *InstancePtr);
u32 XVip1_m_IsReady(XVip1_m *InstancePtr);
void XVip1_m_EnableAutoRestart(XVip1_m *InstancePtr);
void XVip1_m_DisableAutoRestart(XVip1_m *InstancePtr);


void XVip1_m_InterruptGlobalEnable(XVip1_m *InstancePtr);
void XVip1_m_InterruptGlobalDisable(XVip1_m *InstancePtr);
void XVip1_m_InterruptEnable(XVip1_m *InstancePtr, u32 Mask);
void XVip1_m_InterruptDisable(XVip1_m *InstancePtr, u32 Mask);
void XVip1_m_InterruptClear(XVip1_m *InstancePtr, u32 Mask);
u32 XVip1_m_InterruptGetEnabled(XVip1_m *InstancePtr);
u32 XVip1_m_InterruptGetStatus(XVip1_m *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
