-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2017.4
-- Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity test_pattern1 is
port (
    src_axi0_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
    src_axi0_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
    src_axi0_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
    src_axi0_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    src_axi0_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    src_axi0_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    src_axi0_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    src_axi0_TVALID : OUT STD_LOGIC;
    src_axi0_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of test_pattern1 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "test_pattern1,hls_ip_2017_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z010clg400-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.264875,HLS_SYN_LAT=1232642,HLS_SYN_TPT=1232642,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=199,HLS_SYN_LUT=963}";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal Loop_loop_height1_pr_U0_ap_start : STD_LOGIC;
    signal Loop_loop_height1_pr_U0_ap_done : STD_LOGIC;
    signal Loop_loop_height1_pr_U0_ap_continue : STD_LOGIC;
    signal Loop_loop_height1_pr_U0_ap_idle : STD_LOGIC;
    signal Loop_loop_height1_pr_U0_ap_ready : STD_LOGIC;
    signal Loop_loop_height1_pr_U0_imag0_0_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_loop_height1_pr_U0_imag0_0_data_stream_0_V_write : STD_LOGIC;
    signal Loop_loop_height1_pr_U0_imag0_0_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_loop_height1_pr_U0_imag0_0_data_stream_1_V_write : STD_LOGIC;
    signal Loop_loop_height1_pr_U0_imag0_0_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal Loop_loop_height1_pr_U0_imag0_0_data_stream_2_V_write : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_start : STD_LOGIC := '0';
    signal Mat2AXIvideo_U0_ap_done : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_continue : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_idle : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_ready : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_0_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_1_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_2_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_src_axi0_TDATA : STD_LOGIC_VECTOR (23 downto 0);
    signal Mat2AXIvideo_U0_src_axi0_TVALID : STD_LOGIC;
    signal Mat2AXIvideo_U0_src_axi0_TKEEP : STD_LOGIC_VECTOR (2 downto 0);
    signal Mat2AXIvideo_U0_src_axi0_TSTRB : STD_LOGIC_VECTOR (2 downto 0);
    signal Mat2AXIvideo_U0_src_axi0_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_src_axi0_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_src_axi0_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_src_axi0_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal imag0_0_data_stream_s_full_n : STD_LOGIC;
    signal imag0_0_data_stream_s_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal imag0_0_data_stream_s_empty_n : STD_LOGIC;
    signal imag0_0_data_stream_1_full_n : STD_LOGIC;
    signal imag0_0_data_stream_1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal imag0_0_data_stream_1_empty_n : STD_LOGIC;
    signal imag0_0_data_stream_2_full_n : STD_LOGIC;
    signal imag0_0_data_stream_2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal imag0_0_data_stream_2_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal Loop_loop_height1_pr_U0_start_full_n : STD_LOGIC;
    signal Loop_loop_height1_pr_U0_start_write : STD_LOGIC;
    signal Mat2AXIvideo_U0_start_full_n : STD_LOGIC;
    signal Mat2AXIvideo_U0_start_write : STD_LOGIC;

    component Loop_loop_height1_pr IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imag0_0_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        imag0_0_data_stream_0_V_full_n : IN STD_LOGIC;
        imag0_0_data_stream_0_V_write : OUT STD_LOGIC;
        imag0_0_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        imag0_0_data_stream_1_V_full_n : IN STD_LOGIC;
        imag0_0_data_stream_1_V_write : OUT STD_LOGIC;
        imag0_0_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        imag0_0_data_stream_2_V_full_n : IN STD_LOGIC;
        imag0_0_data_stream_2_V_write : OUT STD_LOGIC );
    end component;


    component Mat2AXIvideo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_data_stream_0_V_read : OUT STD_LOGIC;
        img_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_data_stream_1_V_read : OUT STD_LOGIC;
        img_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_2_V_empty_n : IN STD_LOGIC;
        img_data_stream_2_V_read : OUT STD_LOGIC;
        src_axi0_TDATA : OUT STD_LOGIC_VECTOR (23 downto 0);
        src_axi0_TVALID : OUT STD_LOGIC;
        src_axi0_TREADY : IN STD_LOGIC;
        src_axi0_TKEEP : OUT STD_LOGIC_VECTOR (2 downto 0);
        src_axi0_TSTRB : OUT STD_LOGIC_VECTOR (2 downto 0);
        src_axi0_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        src_axi0_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        src_axi0_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        src_axi0_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fifo_w8_d1_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    Loop_loop_height1_pr_U0 : component Loop_loop_height1_pr
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Loop_loop_height1_pr_U0_ap_start,
        ap_done => Loop_loop_height1_pr_U0_ap_done,
        ap_continue => Loop_loop_height1_pr_U0_ap_continue,
        ap_idle => Loop_loop_height1_pr_U0_ap_idle,
        ap_ready => Loop_loop_height1_pr_U0_ap_ready,
        imag0_0_data_stream_0_V_din => Loop_loop_height1_pr_U0_imag0_0_data_stream_0_V_din,
        imag0_0_data_stream_0_V_full_n => imag0_0_data_stream_s_full_n,
        imag0_0_data_stream_0_V_write => Loop_loop_height1_pr_U0_imag0_0_data_stream_0_V_write,
        imag0_0_data_stream_1_V_din => Loop_loop_height1_pr_U0_imag0_0_data_stream_1_V_din,
        imag0_0_data_stream_1_V_full_n => imag0_0_data_stream_1_full_n,
        imag0_0_data_stream_1_V_write => Loop_loop_height1_pr_U0_imag0_0_data_stream_1_V_write,
        imag0_0_data_stream_2_V_din => Loop_loop_height1_pr_U0_imag0_0_data_stream_2_V_din,
        imag0_0_data_stream_2_V_full_n => imag0_0_data_stream_2_full_n,
        imag0_0_data_stream_2_V_write => Loop_loop_height1_pr_U0_imag0_0_data_stream_2_V_write);

    Mat2AXIvideo_U0 : component Mat2AXIvideo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Mat2AXIvideo_U0_ap_start,
        ap_done => Mat2AXIvideo_U0_ap_done,
        ap_continue => Mat2AXIvideo_U0_ap_continue,
        ap_idle => Mat2AXIvideo_U0_ap_idle,
        ap_ready => Mat2AXIvideo_U0_ap_ready,
        img_data_stream_0_V_dout => imag0_0_data_stream_s_dout,
        img_data_stream_0_V_empty_n => imag0_0_data_stream_s_empty_n,
        img_data_stream_0_V_read => Mat2AXIvideo_U0_img_data_stream_0_V_read,
        img_data_stream_1_V_dout => imag0_0_data_stream_1_dout,
        img_data_stream_1_V_empty_n => imag0_0_data_stream_1_empty_n,
        img_data_stream_1_V_read => Mat2AXIvideo_U0_img_data_stream_1_V_read,
        img_data_stream_2_V_dout => imag0_0_data_stream_2_dout,
        img_data_stream_2_V_empty_n => imag0_0_data_stream_2_empty_n,
        img_data_stream_2_V_read => Mat2AXIvideo_U0_img_data_stream_2_V_read,
        src_axi0_TDATA => Mat2AXIvideo_U0_src_axi0_TDATA,
        src_axi0_TVALID => Mat2AXIvideo_U0_src_axi0_TVALID,
        src_axi0_TREADY => src_axi0_TREADY,
        src_axi0_TKEEP => Mat2AXIvideo_U0_src_axi0_TKEEP,
        src_axi0_TSTRB => Mat2AXIvideo_U0_src_axi0_TSTRB,
        src_axi0_TUSER => Mat2AXIvideo_U0_src_axi0_TUSER,
        src_axi0_TLAST => Mat2AXIvideo_U0_src_axi0_TLAST,
        src_axi0_TID => Mat2AXIvideo_U0_src_axi0_TID,
        src_axi0_TDEST => Mat2AXIvideo_U0_src_axi0_TDEST);

    imag0_0_data_stream_s_U : component fifo_w8_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_loop_height1_pr_U0_imag0_0_data_stream_0_V_din,
        if_full_n => imag0_0_data_stream_s_full_n,
        if_write => Loop_loop_height1_pr_U0_imag0_0_data_stream_0_V_write,
        if_dout => imag0_0_data_stream_s_dout,
        if_empty_n => imag0_0_data_stream_s_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_0_V_read);

    imag0_0_data_stream_1_U : component fifo_w8_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_loop_height1_pr_U0_imag0_0_data_stream_1_V_din,
        if_full_n => imag0_0_data_stream_1_full_n,
        if_write => Loop_loop_height1_pr_U0_imag0_0_data_stream_1_V_write,
        if_dout => imag0_0_data_stream_1_dout,
        if_empty_n => imag0_0_data_stream_1_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_1_V_read);

    imag0_0_data_stream_2_U : component fifo_w8_d1_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => Loop_loop_height1_pr_U0_imag0_0_data_stream_2_V_din,
        if_full_n => imag0_0_data_stream_2_full_n,
        if_write => Loop_loop_height1_pr_U0_imag0_0_data_stream_2_V_write,
        if_dout => imag0_0_data_stream_2_dout,
        if_empty_n => imag0_0_data_stream_2_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_2_V_read);





    Mat2AXIvideo_U0_ap_start_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                Mat2AXIvideo_U0_ap_start <= ap_const_logic_0;
            else
                Mat2AXIvideo_U0_ap_start <= ap_const_logic_1;
            end if;
        end if;
    end process;

    Loop_loop_height1_pr_U0_ap_continue <= ap_const_logic_1;
    Loop_loop_height1_pr_U0_ap_start <= ap_start;
    Loop_loop_height1_pr_U0_start_full_n <= ap_const_logic_1;
    Loop_loop_height1_pr_U0_start_write <= ap_const_logic_0;
    Mat2AXIvideo_U0_ap_continue <= ap_const_logic_1;
    Mat2AXIvideo_U0_start_full_n <= ap_const_logic_1;
    Mat2AXIvideo_U0_start_write <= ap_const_logic_0;
    ap_done <= Mat2AXIvideo_U0_ap_done;
    ap_idle <= (Mat2AXIvideo_U0_ap_idle and Loop_loop_height1_pr_U0_ap_idle);
    ap_ready <= Mat2AXIvideo_U0_ap_done;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= Mat2AXIvideo_U0_ap_done;
    ap_sync_ready <= ap_sync_done;
    src_axi0_TDATA <= Mat2AXIvideo_U0_src_axi0_TDATA;
    src_axi0_TDEST <= Mat2AXIvideo_U0_src_axi0_TDEST;
    src_axi0_TID <= Mat2AXIvideo_U0_src_axi0_TID;
    src_axi0_TKEEP <= Mat2AXIvideo_U0_src_axi0_TKEEP;
    src_axi0_TLAST <= Mat2AXIvideo_U0_src_axi0_TLAST;
    src_axi0_TSTRB <= Mat2AXIvideo_U0_src_axi0_TSTRB;
    src_axi0_TUSER <= Mat2AXIvideo_U0_src_axi0_TUSER;
    src_axi0_TVALID <= Mat2AXIvideo_U0_src_axi0_TVALID;
end behav;
