// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xvip1_m.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XVip1_m_CfgInitialize(XVip1_m *InstancePtr, XVip1_m_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XVip1_m_Start(XVip1_m *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVip1_m_ReadReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XVip1_m_WriteReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XVip1_m_IsDone(XVip1_m *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVip1_m_ReadReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XVip1_m_IsIdle(XVip1_m *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVip1_m_ReadReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XVip1_m_IsReady(XVip1_m *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XVip1_m_ReadReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XVip1_m_EnableAutoRestart(XVip1_m *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVip1_m_WriteReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XVip1_m_DisableAutoRestart(XVip1_m *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVip1_m_WriteReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XVip1_m_InterruptGlobalEnable(XVip1_m *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVip1_m_WriteReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_GIE, 1);
}

void XVip1_m_InterruptGlobalDisable(XVip1_m *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVip1_m_WriteReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_GIE, 0);
}

void XVip1_m_InterruptEnable(XVip1_m *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XVip1_m_ReadReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_IER);
    XVip1_m_WriteReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XVip1_m_InterruptDisable(XVip1_m *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XVip1_m_ReadReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_IER);
    XVip1_m_WriteReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XVip1_m_InterruptClear(XVip1_m *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XVip1_m_WriteReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XVip1_m_InterruptGetEnabled(XVip1_m *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XVip1_m_ReadReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_IER);
}

u32 XVip1_m_InterruptGetStatus(XVip1_m *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XVip1_m_ReadReg(InstancePtr->Control_bus_BaseAddress, XVIP1_M_CONTROL_BUS_ADDR_ISR);
}

