webtalk_init -webtalk_dir D:\\BaiduNetdiskDownload\\P10_SD_VGA_m\\SD_VGA.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2020-09-20 10:28:54" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "l7nm5opbp3re9gf3nd9v5ptoh7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_17" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "17" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3292 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.485 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1600565724300" -context "sdk\\\\bsp/1600565724300"
webtalk_add_data -client sdk -key hwid -value "1587389524621" -context "sdk\\\\bsp/1600565724300"
webtalk_add_data -client sdk -key os -value "device_tree" -context "sdk\\\\bsp/1600565724300"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1600565724300"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1600565724300"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1600568934914"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1600568934914"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1600568934914"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1600568934914"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1600568934914"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1600568934914"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1600568934914"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1600568934914"
webtalk_transmit -clientid 2669635725 -regid "" -xml D:\\BaiduNetdiskDownload\\P10_SD_VGA_m\\SD_VGA.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\BaiduNetdiskDownload\\P10_SD_VGA_m\\SD_VGA.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\BaiduNetdiskDownload\\P10_SD_VGA_m\\SD_VGA.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
