// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Loop_loop_height1_pr (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        imag0_0_data_stream_0_V_din,
        imag0_0_data_stream_0_V_full_n,
        imag0_0_data_stream_0_V_write,
        imag0_0_data_stream_1_V_din,
        imag0_0_data_stream_1_V_full_n,
        imag0_0_data_stream_1_V_write,
        imag0_0_data_stream_2_V_din,
        imag0_0_data_stream_2_V_full_n,
        imag0_0_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [7:0] imag0_0_data_stream_0_V_din;
input   imag0_0_data_stream_0_V_full_n;
output   imag0_0_data_stream_0_V_write;
output  [7:0] imag0_0_data_stream_1_V_din;
input   imag0_0_data_stream_1_V_full_n;
output   imag0_0_data_stream_1_V_write;
output  [7:0] imag0_0_data_stream_2_V_din;
input   imag0_0_data_stream_2_V_full_n;
output   imag0_0_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imag0_0_data_stream_0_V_write;
reg imag0_0_data_stream_1_V_write;
reg imag0_0_data_stream_2_V_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    imag0_0_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_2_i_reg_399;
reg    imag0_0_data_stream_1_V_blk_n;
reg    imag0_0_data_stream_2_V_blk_n;
reg   [10:0] t_V_1_reg_114;
wire   [0:0] tmp_i_fu_312_p2;
wire    ap_CS_fsm_state2;
wire   [9:0] i_V_fu_318_p2;
reg   [9:0] i_V_reg_390;
wire   [0:0] tmp_1_i_fu_324_p2;
reg   [0:0] tmp_1_i_reg_395;
wire   [0:0] tmp_2_i_fu_330_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [10:0] j_V_fu_336_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] tmp_4_i_fu_342_p2;
wire   [0:0] grp_fu_276_p2;
wire   [0:0] grp_fu_282_p2;
wire   [0:0] grp_fu_288_p2;
wire   [0:0] grp_fu_294_p2;
wire   [0:0] grp_fu_300_p2;
wire   [7:0] storemerge3_fu_348_p3;
wire   [7:0] storemerge_fu_356_p3;
wire   [7:0] storemerge1_fu_364_p3;
wire   [7:0] storemerge2_cast_fu_378_p3;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg   [9:0] t_V_reg_103;
reg    ap_block_state1;
wire    ap_CS_fsm_state5;
wire   [7:0] ap_phi_reg_pp0_iter0_tmp_4_reg_125;
reg   [7:0] ap_phi_reg_pp0_iter1_tmp_4_reg_125;
wire   [7:0] ap_phi_reg_pp0_iter0_tmp_5_reg_176;
reg   [7:0] ap_phi_reg_pp0_iter1_tmp_5_reg_176;
wire   [7:0] ap_phi_reg_pp0_iter0_tmp_6_reg_225;
reg   [7:0] ap_phi_reg_pp0_iter1_tmp_6_reg_225;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] grp_fu_306_p2;
wire   [0:0] not_tmp_15_i_fu_372_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((tmp_i_fu_312_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((tmp_i_fu_312_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((tmp_i_fu_312_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_300_p2 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_tmp_4_reg_125 <= 8'd64;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_300_p2 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_tmp_4_reg_125 <= 8'd128;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_300_p2 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_tmp_4_reg_125 <= storemerge1_fu_364_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_276_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_282_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_300_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_276_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_288_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_tmp_4_reg_125 <= 8'd0;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_4_i_fu_342_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_288_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_294_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_4_i_fu_342_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_282_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_294_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_tmp_4_reg_125 <= 8'd255;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_tmp_4_reg_125 <= ap_phi_reg_pp0_iter0_tmp_4_reg_125;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_300_p2 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_tmp_5_reg_176 <= storemerge3_fu_348_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_300_p2 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_tmp_5_reg_176 <= storemerge2_cast_fu_378_p3;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_294_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_294_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_tmp_5_reg_176 <= 8'd128;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_276_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_288_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_300_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_4_i_fu_342_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_276_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_300_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_tmp_5_reg_176 <= 8'd255;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_4_i_fu_342_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_282_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_282_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_288_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_tmp_5_reg_176 <= 8'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_tmp_5_reg_176 <= ap_phi_reg_pp0_iter0_tmp_5_reg_176;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_300_p2 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_tmp_6_reg_225 <= storemerge_fu_356_p3;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_294_p2 == 1'd1))) begin
        ap_phi_reg_pp0_iter1_tmp_6_reg_225 <= 8'd64;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_300_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_300_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_tmp_6_reg_225 <= 8'd128;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_282_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_288_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_300_p2 == 1'd0) & (grp_fu_294_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_276_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_282_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_tmp_6_reg_225 <= 8'd255;
    end else if ((((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_4_i_fu_342_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_276_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_1_i_reg_395 == 1'd1) & (tmp_2_i_fu_330_p2 == 1'd0) & (grp_fu_288_p2 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_294_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (tmp_4_i_fu_342_p2 == 1'd1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (tmp_1_i_reg_395 == 1'd0) & (grp_fu_282_p2 == 1'd0) & (grp_fu_276_p2 == 1'd0) & (tmp_4_i_fu_342_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (grp_fu_288_p2 == 1'd1)))) begin
        ap_phi_reg_pp0_iter1_tmp_6_reg_225 <= 8'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter1_tmp_6_reg_225 <= ap_phi_reg_pp0_iter0_tmp_6_reg_225;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_fu_330_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        t_V_1_reg_114 <= j_V_fu_336_p2;
    end else if (((tmp_i_fu_312_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_1_reg_114 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        t_V_reg_103 <= i_V_reg_390;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_103 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        i_V_reg_390 <= i_V_fu_318_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_i_fu_312_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_1_i_reg_395 <= tmp_1_i_fu_324_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_2_i_reg_399 <= tmp_2_i_fu_330_p2;
    end
end

always @ (*) begin
    if ((tmp_2_i_fu_330_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_fu_312_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_i_fu_312_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_i_reg_399 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag0_0_data_stream_0_V_blk_n = imag0_0_data_stream_0_V_full_n;
    end else begin
        imag0_0_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_reg_399 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag0_0_data_stream_0_V_write = 1'b1;
    end else begin
        imag0_0_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_i_reg_399 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag0_0_data_stream_1_V_blk_n = imag0_0_data_stream_1_V_full_n;
    end else begin
        imag0_0_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_reg_399 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag0_0_data_stream_1_V_write = 1'b1;
    end else begin
        imag0_0_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_2_i_reg_399 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag0_0_data_stream_2_V_blk_n = imag0_0_data_stream_2_V_full_n;
    end else begin
        imag0_0_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_2_i_reg_399 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        imag0_0_data_stream_2_V_write = 1'b1;
    end else begin
        imag0_0_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_i_fu_312_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((tmp_2_i_fu_330_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((tmp_2_i_fu_330_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_2_V_full_n == 1'b0)) | ((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_1_V_full_n == 1'b0)) | ((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_0_V_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_2_V_full_n == 1'b0)) | ((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_1_V_full_n == 1'b0)) | ((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_0_V_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_2_V_full_n == 1'b0)) | ((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_1_V_full_n == 1'b0)) | ((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_0_V_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_2_V_full_n == 1'b0)) | ((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_1_V_full_n == 1'b0)) | ((tmp_2_i_reg_399 == 1'd0) & (imag0_0_data_stream_0_V_full_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_tmp_4_reg_125 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_5_reg_176 = 'bx;

assign ap_phi_reg_pp0_iter0_tmp_6_reg_225 = 'bx;

assign grp_fu_276_p2 = ((t_V_1_reg_114 < 11'd320) ? 1'b1 : 1'b0);

assign grp_fu_282_p2 = ((t_V_1_reg_114 < 11'd480) ? 1'b1 : 1'b0);

assign grp_fu_288_p2 = ((t_V_1_reg_114 < 11'd640) ? 1'b1 : 1'b0);

assign grp_fu_294_p2 = ((t_V_1_reg_114 < 11'd800) ? 1'b1 : 1'b0);

assign grp_fu_300_p2 = ((t_V_1_reg_114 < 11'd960) ? 1'b1 : 1'b0);

assign grp_fu_306_p2 = ((t_V_1_reg_114 < 11'd1120) ? 1'b1 : 1'b0);

assign i_V_fu_318_p2 = (t_V_reg_103 + 10'd1);

assign imag0_0_data_stream_0_V_din = ap_phi_reg_pp0_iter1_tmp_4_reg_125;

assign imag0_0_data_stream_1_V_din = ap_phi_reg_pp0_iter1_tmp_5_reg_176;

assign imag0_0_data_stream_2_V_din = ap_phi_reg_pp0_iter1_tmp_6_reg_225;

assign j_V_fu_336_p2 = (t_V_1_reg_114 + 11'd1);

assign not_tmp_15_i_fu_372_p2 = (grp_fu_306_p2 ^ 1'd1);

assign storemerge1_fu_364_p3 = ((grp_fu_306_p2[0:0] === 1'b1) ? 8'd128 : 8'd255);

assign storemerge2_cast_fu_378_p3 = ((not_tmp_15_i_fu_372_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign storemerge3_fu_348_p3 = ((grp_fu_306_p2[0:0] === 1'b1) ? 8'd64 : 8'd128);

assign storemerge_fu_356_p3 = ((grp_fu_306_p2[0:0] === 1'b1) ? 8'd255 : 8'd128);

assign tmp_1_i_fu_324_p2 = ((t_V_reg_103 < 10'd480) ? 1'b1 : 1'b0);

assign tmp_2_i_fu_330_p2 = ((t_V_1_reg_114 == 11'd1280) ? 1'b1 : 1'b0);

assign tmp_4_i_fu_342_p2 = ((t_V_1_reg_114 < 11'd160) ? 1'b1 : 1'b0);

assign tmp_i_fu_312_p2 = ((t_V_reg_103 == 10'd960) ? 1'b1 : 1'b0);

endmodule //Loop_loop_height1_pr
