// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xtest_pattern1.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XTest_pattern1_CfgInitialize(XTest_pattern1 *InstancePtr, XTest_pattern1_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XTest_pattern1_Start(XTest_pattern1 *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_pattern1_ReadReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XTest_pattern1_WriteReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XTest_pattern1_IsDone(XTest_pattern1 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_pattern1_ReadReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XTest_pattern1_IsIdle(XTest_pattern1 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_pattern1_ReadReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XTest_pattern1_IsReady(XTest_pattern1 *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTest_pattern1_ReadReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XTest_pattern1_EnableAutoRestart(XTest_pattern1 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_pattern1_WriteReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XTest_pattern1_DisableAutoRestart(XTest_pattern1 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_pattern1_WriteReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XTest_pattern1_InterruptGlobalEnable(XTest_pattern1 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_pattern1_WriteReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_GIE, 1);
}

void XTest_pattern1_InterruptGlobalDisable(XTest_pattern1 *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_pattern1_WriteReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_GIE, 0);
}

void XTest_pattern1_InterruptEnable(XTest_pattern1 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTest_pattern1_ReadReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_IER);
    XTest_pattern1_WriteReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XTest_pattern1_InterruptDisable(XTest_pattern1 *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTest_pattern1_ReadReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_IER);
    XTest_pattern1_WriteReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XTest_pattern1_InterruptClear(XTest_pattern1 *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTest_pattern1_WriteReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XTest_pattern1_InterruptGetEnabled(XTest_pattern1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTest_pattern1_ReadReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_IER);
}

u32 XTest_pattern1_InterruptGetStatus(XTest_pattern1 *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTest_pattern1_ReadReg(InstancePtr->Control_bus_BaseAddress, XTEST_PATTERN1_CONTROL_BUS_ADDR_ISR);
}

