vlib questa_lib/work
vlib questa_lib/msim

vlib questa_lib/msim/xil_defaultlib
vlib questa_lib/msim/xpm
vlib questa_lib/msim/axi_infrastructure_v1_1_0
vlib questa_lib/msim/smartconnect_v1_0
vlib questa_lib/msim/axi_protocol_checker_v2_0_1
vlib questa_lib/msim/axi_vip_v1_1_1
vlib questa_lib/msim/processing_system7_vip_v1_0_3
vlib questa_lib/msim/lib_cdc_v1_0_2
vlib questa_lib/msim/lib_pkg_v1_0_2
vlib questa_lib/msim/fifo_generator_v13_2_1
vlib questa_lib/msim/lib_fifo_v1_0_10
vlib questa_lib/msim/blk_mem_gen_v8_4_1
vlib questa_lib/msim/lib_bmg_v1_0_10
vlib questa_lib/msim/lib_srl_fifo_v1_0_2
vlib questa_lib/msim/axi_datamover_v5_1_17
vlib questa_lib/msim/axi_vdma_v6_3_3
vlib questa_lib/msim/proc_sys_reset_v5_0_12
vlib questa_lib/msim/axi_lite_ipif_v3_0_4
vlib questa_lib/msim/v_tc_v6_1_12
vlib questa_lib/msim/v_vid_in_axi4s_v4_0_7
vlib questa_lib/msim/v_axi4s_vid_out_v4_0_8
vlib questa_lib/msim/util_vector_logic_v2_0_1
vlib questa_lib/msim/xlconstant_v1_1_3
vlib questa_lib/msim/generic_baseblocks_v2_1_0
vlib questa_lib/msim/axi_register_slice_v2_1_15
vlib questa_lib/msim/axi_data_fifo_v2_1_14
vlib questa_lib/msim/axi_crossbar_v2_1_16
vlib questa_lib/msim/xlconcat_v2_1_1
vlib questa_lib/msim/axi_protocol_converter_v2_1_15

vmap xil_defaultlib questa_lib/msim/xil_defaultlib
vmap xpm questa_lib/msim/xpm
vmap axi_infrastructure_v1_1_0 questa_lib/msim/axi_infrastructure_v1_1_0
vmap smartconnect_v1_0 questa_lib/msim/smartconnect_v1_0
vmap axi_protocol_checker_v2_0_1 questa_lib/msim/axi_protocol_checker_v2_0_1
vmap axi_vip_v1_1_1 questa_lib/msim/axi_vip_v1_1_1
vmap processing_system7_vip_v1_0_3 questa_lib/msim/processing_system7_vip_v1_0_3
vmap lib_cdc_v1_0_2 questa_lib/msim/lib_cdc_v1_0_2
vmap lib_pkg_v1_0_2 questa_lib/msim/lib_pkg_v1_0_2
vmap fifo_generator_v13_2_1 questa_lib/msim/fifo_generator_v13_2_1
vmap lib_fifo_v1_0_10 questa_lib/msim/lib_fifo_v1_0_10
vmap blk_mem_gen_v8_4_1 questa_lib/msim/blk_mem_gen_v8_4_1
vmap lib_bmg_v1_0_10 questa_lib/msim/lib_bmg_v1_0_10
vmap lib_srl_fifo_v1_0_2 questa_lib/msim/lib_srl_fifo_v1_0_2
vmap axi_datamover_v5_1_17 questa_lib/msim/axi_datamover_v5_1_17
vmap axi_vdma_v6_3_3 questa_lib/msim/axi_vdma_v6_3_3
vmap proc_sys_reset_v5_0_12 questa_lib/msim/proc_sys_reset_v5_0_12
vmap axi_lite_ipif_v3_0_4 questa_lib/msim/axi_lite_ipif_v3_0_4
vmap v_tc_v6_1_12 questa_lib/msim/v_tc_v6_1_12
vmap v_vid_in_axi4s_v4_0_7 questa_lib/msim/v_vid_in_axi4s_v4_0_7
vmap v_axi4s_vid_out_v4_0_8 questa_lib/msim/v_axi4s_vid_out_v4_0_8
vmap util_vector_logic_v2_0_1 questa_lib/msim/util_vector_logic_v2_0_1
vmap xlconstant_v1_1_3 questa_lib/msim/xlconstant_v1_1_3
vmap generic_baseblocks_v2_1_0 questa_lib/msim/generic_baseblocks_v2_1_0
vmap axi_register_slice_v2_1_15 questa_lib/msim/axi_register_slice_v2_1_15
vmap axi_data_fifo_v2_1_14 questa_lib/msim/axi_data_fifo_v2_1_14
vmap axi_crossbar_v2_1_16 questa_lib/msim/axi_crossbar_v2_1_16
vmap xlconcat_v2_1_1 questa_lib/msim/xlconcat_v2_1_1
vmap axi_protocol_converter_v2_1_15 questa_lib/msim/axi_protocol_converter_v2_1_15

vlog -work xil_defaultlib -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L processing_system7_vip_v1_0_3 -L xilinx_vip "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"D:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
"D:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
"D:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vcom -work xpm -64 -93 \
"D:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd" \

vlog -work axi_infrastructure_v1_1_0 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \

vlog -work smartconnect_v1_0 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L processing_system7_vip_v1_0_3 -L xilinx_vip "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/sc_util_v1_0_vl_rfs.sv" \

vlog -work axi_protocol_checker_v2_0_1 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L processing_system7_vip_v1_0_3 -L xilinx_vip "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/3b24/hdl/axi_protocol_checker_v2_0_vl_rfs.sv" \

vlog -work axi_vip_v1_1_1 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L processing_system7_vip_v1_0_3 -L xilinx_vip "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a16a/hdl/axi_vip_v1_1_vl_rfs.sv" \

vlog -work processing_system7_vip_v1_0_3 -64 -sv -L smartconnect_v1_0 -L axi_protocol_checker_v2_0_1 -L axi_vip_v1_1_1 -L processing_system7_vip_v1_0_3 -L xilinx_vip "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \

vlog -work xil_defaultlib -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zynq_sys/ip/zynq_sys_processing_system7_0_0/sim/zynq_sys_processing_system7_0_0.v" \

vcom -work lib_cdc_v1_0_2 -64 -93 \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \

vcom -work lib_pkg_v1_0_2 -64 -93 \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \

vlog -work fifo_generator_v13_2_1 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/5c35/simulation/fifo_generator_vlog_beh.v" \

vcom -work fifo_generator_v13_2_1 -64 -93 \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -work fifo_generator_v13_2_1 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/5c35/hdl/fifo_generator_v13_2_rfs.v" \

vcom -work lib_fifo_v1_0_10 -64 -93 \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f10a/hdl/lib_fifo_v1_0_rfs.vhd" \

vlog -work blk_mem_gen_v8_4_1 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/67d8/simulation/blk_mem_gen_v8_4.v" \

vcom -work lib_bmg_v1_0_10 -64 -93 \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9340/hdl/lib_bmg_v1_0_rfs.vhd" \

vcom -work lib_srl_fifo_v1_0_2 -64 -93 \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \

vcom -work axi_datamover_v5_1_17 -64 -93 \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/71f3/hdl/axi_datamover_v5_1_vh_rfs.vhd" \

vlog -work axi_vdma_v6_3_3 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl/axi_vdma_v6_3_rfs.v" \

vcom -work axi_vdma_v6_3_3 -64 -93 \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl/axi_vdma_v6_3_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/zynq_sys/ip/zynq_sys_axi_vdma_0_0/sim/zynq_sys_axi_vdma_0_0.vhd" \

vcom -work proc_sys_reset_v5_0_12 -64 -93 \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f86a/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/zynq_sys/ip/zynq_sys_rst_ps7_0_50M_0/sim/zynq_sys_rst_ps7_0_50M_0.vhd" \

vcom -work axi_lite_ipif_v3_0_4 -64 -93 \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/cced/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \

vcom -work v_tc_v6_1_12 -64 -93 \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6694/hdl/v_tc_v6_1_vh_rfs.vhd" \

vcom -work xil_defaultlib -64 -93 \
"../../../bd/zynq_sys/ip/zynq_sys_v_tc_0_0/sim/zynq_sys_v_tc_0_0.vhd" \

vlog -work v_vid_in_axi4s_v4_0_7 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f931/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \

vlog -work v_axi4s_vid_out_v4_0_8 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/fc47/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \

vlog -work xil_defaultlib -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zynq_sys/ip/zynq_sys_v_axi4s_vid_out_0_0/sim/zynq_sys_v_axi4s_vid_out_0_0.v" \
"../../../bd/zynq_sys/ip/zynq_sys_clk_wiz_0_0/zynq_sys_clk_wiz_0_0_clk_wiz.v" \
"../../../bd/zynq_sys/ip/zynq_sys_clk_wiz_0_0/zynq_sys_clk_wiz_0_0.v" \

vlog -work util_vector_logic_v2_0_1 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \

vlog -work xil_defaultlib -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zynq_sys/ip/zynq_sys_util_vector_logic_0_0/sim/zynq_sys_util_vector_logic_0_0.v" \
"../../../bd/zynq_sys/ipshared/4d05/VGA_OUT.v" \
"../../../bd/zynq_sys/ip/zynq_sys_VGA_OUT_0_0/sim/zynq_sys_VGA_OUT_0_0.v" \
"../../../bd/zynq_sys/ipshared/0aa8/MSXBO_OVSensorRGB565.v" \
"../../../bd/zynq_sys/ip/zynq_sys_MSXBO_OVSensorRGB565_0_0/sim/zynq_sys_MSXBO_OVSensorRGB565_0_0.v" \
"../../../bd/zynq_sys/ip/zynq_sys_v_vid_in_axi4s_0_0/sim/zynq_sys_v_vid_in_axi4s_0_0.v" \

vlog -work xlconstant_v1_1_3 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/0750/hdl/xlconstant_v1_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zynq_sys/ip/zynq_sys_xlconstant_0_0/sim/zynq_sys_xlconstant_0_0.v" \
"../../../bd/zynq_sys/ip/zynq_sys_xlconstant_1_0/sim/zynq_sys_xlconstant_1_0.v" \
"../../../bd/zynq_sys/sim/zynq_sys.v" \

vlog -work generic_baseblocks_v2_1_0 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \

vlog -work axi_register_slice_v2_1_15 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/3ed1/hdl/axi_register_slice_v2_1_vl_rfs.v" \

vlog -work axi_data_fifo_v2_1_14 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9909/hdl/axi_data_fifo_v2_1_vl_rfs.v" \

vlog -work axi_crossbar_v2_1_16 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/c631/hdl/axi_crossbar_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zynq_sys/ip/zynq_sys_xbar_0/sim/zynq_sys_xbar_0.v" \
"../../../bd/zynq_sys/ip/zynq_sys_system_ila_1_0/bd_0/sim/bd_ed1d.v" \
"../../../bd/zynq_sys/ip/zynq_sys_system_ila_1_0/bd_0/ip/ip_0/sim/bd_ed1d_ila_lib_0.v" \
"../../../bd/zynq_sys/ip/zynq_sys_system_ila_1_0/sim/zynq_sys_system_ila_1_0.v" \

vlog -work xlconcat_v2_1_1 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/2f66/hdl/xlconcat_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zynq_sys/ip/zynq_sys_xlconcat_0_0/sim/zynq_sys_xlconcat_0_0.v" \
"../../../bd/zynq_sys/ip/zynq_sys_xlconcat_1_0/sim/zynq_sys_xlconcat_1_0.v" \
"../../../bd/zynq_sys/ip/zynq_sys_xlconstant_2_0/sim/zynq_sys_xlconstant_2_0.v" \
"../../../bd/zynq_sys/ip/zynq_sys_xbar_1/sim/zynq_sys_xbar_1.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/AXIvideo2Mat.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/AXIvideo2Mat47.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/fifo_w8_d1_A.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/fifo_w8_d640_A.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/Loop_loop_height_pro.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/Mat2AXIvideo.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/start_for_Loop_locud.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/start_for_Mat2AXIdEe.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/vip1.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/vip1_ap_rst_n_if.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/vip1_CONTROL_BUS_if.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/vip1_mul_mul_10nsbkb.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/9e7a/hdl/verilog/vip1_top.v" \
"../../../bd/zynq_sys/ip/zynq_sys_vip1_0_1/sim/zynq_sys_vip1_0_1.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/8cec/hdl/verilog/Loop_loop_height1_pr.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/8cec/hdl/verilog/Mat2AXIvideo.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/8cec/hdl/verilog/test_pattern.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/8cec/hdl/verilog/test_pattern_ap_rst_n_if.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/8cec/hdl/verilog/test_pattern_CONTROL_BUS_if.v" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/8cec/hdl/verilog/test_pattern_top.v" \
"../../../bd/zynq_sys/ip/zynq_sys_test_pattern_0_1/sim/zynq_sys_test_pattern_0_1.v" \

vlog -work axi_protocol_converter_v2_1_15 -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ff69/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \

vlog -work xil_defaultlib -64 "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/ec67/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/02c8/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/1313/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/f8d8/hdl" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/4868" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6180/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/a08d/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/6851/hdl/verilog" "+incdir+../../../../SD_VGA.srcs/sources_1/bd/zynq_sys/ipshared/82bb/hdl/verilog" "+incdir+D:/Xilinx/Vivado/2017.4/data/xilinx_vip/include" \
"../../../bd/zynq_sys/ip/zynq_sys_auto_pc_1/sim/zynq_sys_auto_pc_1.v" \
"../../../bd/zynq_sys/ip/zynq_sys_auto_pc_0/sim/zynq_sys_auto_pc_0.v" \

vlog -work xil_defaultlib \
"glbl.v"

