
set_property PACKAGE_PIN J18 [get_ports {vga_r_0[0]}]
set_property PACKAGE_PIN G19 [get_ports {vga_r_0[1]}]
set_property PACKAGE_PIN H20 [get_ports {vga_r_0[2]}]
set_property PACKAGE_PIN J19 [get_ports {vga_r_0[3]}]
set_property PACKAGE_PIN K18 [get_ports {vga_r_0[4]}]
set_property PACKAGE_PIN K19 [get_ports {vga_r_0[5]}]
set_property PACKAGE_PIN J20 [get_ports {vga_r_0[6]}]
set_property PACKAGE_PIN L16 [get_ports {vga_r_0[7]}]


set_property PACKAGE_PIN L19 [get_ports {vga_g_0[0]}]
set_property PACKAGE_PIN M18 [get_ports {vga_g_0[1]}]
set_property PACKAGE_PIN L20 [get_ports {vga_g_0[2]}]
set_property PACKAGE_PIN M20 [get_ports {vga_g_0[3]}]
set_property PACKAGE_PIN L17 [get_ports {vga_g_0[4]}]
set_property PACKAGE_PIN M19 [get_ports {vga_g_0[5]}]
set_property PACKAGE_PIN N20 [get_ports {vga_g_0[6]}]
set_property PACKAGE_PIN P18 [get_ports {vga_g_0[7]}]



set_property PACKAGE_PIN M17 [get_ports {vga_b_0[0]}]
set_property PACKAGE_PIN N17 [get_ports {vga_b_0[1]}]
set_property PACKAGE_PIN P20 [get_ports {vga_b_0[2]}]
set_property PACKAGE_PIN R18 [get_ports {vga_b_0[3]}]
set_property PACKAGE_PIN R19 [get_ports {vga_b_0[4]}]
set_property PACKAGE_PIN P19 [get_ports {vga_b_0[5]}]
set_property PACKAGE_PIN T20 [get_ports {vga_b_0[6]}]
set_property PACKAGE_PIN U20 [get_ports {vga_b_0[7]}]


set_property PACKAGE_PIN T19 [get_ports vga_clk_0]
set_property PACKAGE_PIN U19 [get_ports vga_hsync_0]
set_property PACKAGE_PIN V20 [get_ports vga_vsync_0]


set_property PACKAGE_PIN G20 [get_ports vga_blank_0]



set_property IOSTANDARD LVCMOS33 [get_ports vga_blank_0]




set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r_0[7]}]


set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g_0[7]}]


set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b_0[7]}]


set_property IOSTANDARD LVCMOS33 [get_ports vga_clk_0]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync_0]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync_0]



set_property PACKAGE_PIN K17 [get_ports IIC_0_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_scl_io]

set_property PACKAGE_PIN F19 [get_ports IIC_0_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports IIC_0_sda_io]
set_property PULLUP true [get_ports IIC_0_sda_io]
set_property PULLUP true [get_ports IIC_0_scl_io]
#---------------------------------------------------------
#set_property -dict {PACKAGE_PIN AF18  IOSTANDARD LVCMOS33} [get_ports cmos_xclk_o]
set_property -dict {PACKAGE_PIN D19 IOSTANDARD LVCMOS33} [get_ports cmos_pclk_i]
#------------------------------------------------------------------------------------------------
set_property -dict {PACKAGE_PIN E19 IOSTANDARD LVCMOS33} [get_ports cmos_vsync_i]
set_property -dict {PACKAGE_PIN F20 IOSTANDARD LVCMOS33} [get_ports cmos_href_i]
set_property -dict {PACKAGE_PIN A20 IOSTANDARD LVCMOS33} [get_ports cmos_reset]
#------------------------------------------------------------------------------------------------
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports {cmos_data_i[0]}]
set_property -dict {PACKAGE_PIN B19 IOSTANDARD LVCMOS33} [get_ports {cmos_data_i[1]}]
set_property -dict {PACKAGE_PIN B20 IOSTANDARD LVCMOS33} [get_ports {cmos_data_i[2]}]
set_property -dict {PACKAGE_PIN C20 IOSTANDARD LVCMOS33} [get_ports {cmos_data_i[3]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {cmos_data_i[4]}]
set_property -dict {PACKAGE_PIN D20 IOSTANDARD LVCMOS33} [get_ports {cmos_data_i[5]}]
set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports {cmos_data_i[6]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {cmos_data_i[7]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets cmos_pclk_i_IBUF]


set_property IOSTANDARD LVCMOS33 [get_ports MDIO_PHY_0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_PHY_0_mdio_io]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_rd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RGMII_0_td[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_rx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_tx_ctl]
set_property IOSTANDARD LVCMOS33 [get_ports RGMII_0_txc]
set_property PACKAGE_PIN W15 [get_ports MDIO_PHY_0_mdc]
set_property PACKAGE_PIN Y14 [get_ports MDIO_PHY_0_mdio_io]
set_property PACKAGE_PIN V17 [get_ports {RGMII_0_rd[2]}]
set_property PACKAGE_PIN V18 [get_ports {RGMII_0_td[2]}]
set_property PACKAGE_PIN W18 [get_ports {RGMII_0_td[0]}]
set_property PACKAGE_PIN V16 [get_ports {RGMII_0_rd[1]}]
set_property PACKAGE_PIN Y19 [get_ports {RGMII_0_td[3]}]
set_property PACKAGE_PIN Y18 [get_ports {RGMII_0_td[1]}]
set_property PACKAGE_PIN Y16 [get_ports {RGMII_0_rd[0]}]
set_property PACKAGE_PIN Y17 [get_ports {RGMII_0_rd[3]}]
set_property PACKAGE_PIN U15 [get_ports RGMII_0_txc]
set_property PACKAGE_PIN U14 [get_ports RGMII_0_rxc]
set_property PACKAGE_PIN W16 [get_ports RGMII_0_rx_ctl]
set_property PACKAGE_PIN W19 [get_ports RGMII_0_tx_ctl]

set_property PACKAGE_PIN U14 [get_ports ENET0_GMII_RX_CLK]
set_property PACKAGE_PIN U15 [get_ports ENET0_GMII_TX_CLK]
set_property PACKAGE_PIN W19 [get_ports {ENET0_GMII_TX_EN[0]}]
set_property PACKAGE_PIN W18 [get_ports {ENET0_GMII_TXD_0[0]}]
set_property PACKAGE_PIN Y18 [get_ports {ENET0_GMII_TXD_0[1]}]
set_property PACKAGE_PIN V18 [get_ports {ENET0_GMII_TXD_0[2]}]
set_property PACKAGE_PIN Y19 [get_ports {ENET0_GMII_TXD_0[3]}]
set_property PACKAGE_PIN Y16 [get_ports {In0[0]}]
set_property PACKAGE_PIN V16 [get_ports {In0[1]}]
set_property PACKAGE_PIN V17 [get_ports {In0[2]}]
set_property PACKAGE_PIN Y17 [get_ports {In0[3]}]
set_property PACKAGE_PIN W16 [get_ports ENET0_GMII_RX_DV]
set_property PACKAGE_PIN W15 [get_ports MDIO_ETHERNET_0_0_mdc]
set_property PACKAGE_PIN Y14 [get_ports MDIO_ETHERNET_0_0_mdio_io]

set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_RX_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_TX_CLK]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TX_EN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD_0[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD_0[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD_0[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD_0[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD_0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD_0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD_0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ENET0_GMII_TXD_0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {In0[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {In0[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {In0[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {In0[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ENET0_GMII_RX_DV]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_ETHERNET_0_0_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports MDIO_ETHERNET_0_0_mdio_io]

set_property PACKAGE_PIN W13 [get_ports {GPIO_0_0_tri_io[0]}]
set_property PACKAGE_PIN W14 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {GPIO_0_0_tri_io[5]}]
set_property PACKAGE_PIN V12 [get_ports {GPIO_0_0_tri_io[2]}]
set_property PACKAGE_PIN U12 [get_ports {GPIO_0_0_tri_io[3]}]
set_property PACKAGE_PIN V15 [get_ports {GPIO_0_0_tri_io[4]}]
set_property PACKAGE_PIN V13 [get_ports {GPIO_0_0_tri_io[5]}]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ENET0_GMII_TX_CLK_IBUF]



set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list zynq_sys_i/v_vid_in_axi4s_0_video_out_TLAST]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list zynq_sys_i/v_vid_in_axi4s_0_video_out_TREADY]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list zynq_sys_i/v_vid_in_axi4s_0_video_out_TUSER]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list zynq_sys_i/v_vid_in_axi4s_0_video_out_TVALID]]


connect_debug_port u_ila_1/probe2 [get_nets [list {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[0]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[1]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[2]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[3]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[4]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[5]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[6]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[7]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[8]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[9]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[10]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[11]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[12]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[13]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[14]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[15]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[16]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[17]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[18]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[19]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[20]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[21]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[22]} {zynq_sys_i/v_vid_in_axi4s_0_video_out_TDATA[23]}]]
connect_debug_port u_ila_1/probe3 [get_nets [list {zynq_sys_i/vip1_m_0_dst_axi_TDATA[0]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[1]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[2]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[3]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[4]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[5]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[6]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[7]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[8]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[9]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[10]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[11]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[12]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[13]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[14]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[15]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[16]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[17]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[18]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[19]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[20]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[21]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[22]} {zynq_sys_i/vip1_m_0_dst_axi_TDATA[23]}]]
connect_debug_port u_ila_1/probe4 [get_nets [list zynq_sys_i/v_vid_in_axi4s_0_video_out_TLAST]]
connect_debug_port u_ila_1/probe5 [get_nets [list zynq_sys_i/v_vid_in_axi4s_0_video_out_TREADY]]
connect_debug_port u_ila_1/probe6 [get_nets [list zynq_sys_i/v_vid_in_axi4s_0_video_out_TUSER]]
connect_debug_port u_ila_1/probe7 [get_nets [list zynq_sys_i/v_vid_in_axi4s_0_video_out_TVALID]]
connect_debug_port u_ila_1/probe8 [get_nets [list zynq_sys_i/vip1_m_0/inst/sig_vip1_m_ap_ready]]
connect_debug_port u_ila_1/probe9 [get_nets [list zynq_sys_i/vip1_m_0/inst/sig_vip1_m_ap_start]]
connect_debug_port u_ila_1/probe10 [get_nets [list zynq_sys_i/vip1_m_0_dst_axi_TLAST]]
connect_debug_port u_ila_1/probe11 [get_nets [list zynq_sys_i/vip1_m_0_dst_axi_TREADY]]
connect_debug_port u_ila_1/probe12 [get_nets [list zynq_sys_i/vip1_m_0_dst_axi_TUSER]]
connect_debug_port u_ila_1/probe13 [get_nets [list zynq_sys_i/vip1_m_0_dst_axi_TVALID]]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list cmos_pclk_i_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {cmos_data_i_IBUF[0]} {cmos_data_i_IBUF[1]} {cmos_data_i_IBUF[2]} {cmos_data_i_IBUF[3]} {cmos_data_i_IBUF[4]} {cmos_data_i_IBUF[5]} {cmos_data_i_IBUF[6]} {cmos_data_i_IBUF[7]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list zynq_sys_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 24 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[0]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[1]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[2]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[3]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[4]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[5]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[6]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[7]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[8]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[9]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[10]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[11]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[12]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[13]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[14]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[15]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[16]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[17]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[18]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[19]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[20]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[21]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[22]} {zynq_sys_i/axi_vdma_0/m_axis_mm2s_tdata[23]}]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list ENET0_GMII_RX_CLK_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list IIC_0_scl_i]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 24 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[0]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[1]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[2]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[3]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[4]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[5]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[6]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[7]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[8]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[9]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[10]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[11]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[12]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[13]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[14]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[15]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[16]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[17]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[18]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[19]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[20]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[21]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[22]} {zynq_sys_i/axi_vdma_0/s_axis_s2mm_tdata[23]}]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe1]
set_property port_width 1 [get_debug_ports u_ila_2/probe1]
connect_debug_port u_ila_2/probe1 [get_nets [list IIC_0_scl_o]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe2]
set_property port_width 1 [get_debug_ports u_ila_2/probe2]
connect_debug_port u_ila_2/probe2 [get_nets [list IIC_0_scl_t]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe3]
set_property port_width 1 [get_debug_ports u_ila_2/probe3]
connect_debug_port u_ila_2/probe3 [get_nets [list IIC_0_sda_i]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe4]
set_property port_width 1 [get_debug_ports u_ila_2/probe4]
connect_debug_port u_ila_2/probe4 [get_nets [list IIC_0_sda_o]]
create_debug_port u_ila_2 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe5]
set_property port_width 1 [get_debug_ports u_ila_2/probe5]
connect_debug_port u_ila_2/probe5 [get_nets [list IIC_0_sda_t]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
