// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xvip1.h"

extern XVip1_Config XVip1_ConfigTable[];

XVip1_Config *XVip1_LookupConfig(u16 DeviceId) {
	XVip1_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XVIP1_NUM_INSTANCES; Index++) {
		if (XVip1_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XVip1_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XVip1_Initialize(XVip1 *InstancePtr, u16 DeviceId) {
	XVip1_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XVip1_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XVip1_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

