// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================


`timescale 1 ns / 1 ps

`define TV_OUT_src_axi0_TDATA "../tv/rtldatafile/rtl.test_pattern1.autotvout_src_axi0_V_data_V.dat"
`define EGRESS_STATUS_src_axi0_TDATA "../tv/stream_size/stream_egress_status_src_axi0_V_data_V.dat"
`define TV_OUT_src_axi0_TKEEP "../tv/rtldatafile/rtl.test_pattern1.autotvout_src_axi0_V_keep_V.dat"
`define EGRESS_STATUS_src_axi0_TKEEP "../tv/stream_size/stream_egress_status_src_axi0_V_keep_V.dat"
`define TV_OUT_src_axi0_TSTRB "../tv/rtldatafile/rtl.test_pattern1.autotvout_src_axi0_V_strb_V.dat"
`define EGRESS_STATUS_src_axi0_TSTRB "../tv/stream_size/stream_egress_status_src_axi0_V_strb_V.dat"
`define TV_OUT_src_axi0_TUSER "../tv/rtldatafile/rtl.test_pattern1.autotvout_src_axi0_V_user_V.dat"
`define EGRESS_STATUS_src_axi0_TUSER "../tv/stream_size/stream_egress_status_src_axi0_V_user_V.dat"
`define TV_OUT_src_axi0_TLAST "../tv/rtldatafile/rtl.test_pattern1.autotvout_src_axi0_V_last_V.dat"
`define EGRESS_STATUS_src_axi0_TLAST "../tv/stream_size/stream_egress_status_src_axi0_V_last_V.dat"
`define TV_OUT_src_axi0_TID "../tv/rtldatafile/rtl.test_pattern1.autotvout_src_axi0_V_id_V.dat"
`define EGRESS_STATUS_src_axi0_TID "../tv/stream_size/stream_egress_status_src_axi0_V_id_V.dat"
`define TV_OUT_src_axi0_TDEST "../tv/rtldatafile/rtl.test_pattern1.autotvout_src_axi0_V_dest_V.dat"
`define EGRESS_STATUS_src_axi0_TDEST "../tv/stream_size/stream_egress_status_src_axi0_V_dest_V.dat"

`define AUTOTB_TRANSACTION_NUM 1

module AESL_axi_s_src_axi0 (
    input clk,
    input reset,
    input [24 - 1:0] TRAN_src_axi0_TDATA,
    input [3 - 1:0] TRAN_src_axi0_TKEEP,
    input [3 - 1:0] TRAN_src_axi0_TSTRB,
    input TRAN_src_axi0_TUSER,
    input TRAN_src_axi0_TLAST,
    input TRAN_src_axi0_TID,
    input TRAN_src_axi0_TDEST,
    input TRAN_src_axi0_TVALID,
    output TRAN_src_axi0_TREADY,
    input ready,
    input done,
    output [31:0] transaction);

    wire TRAN_src_axi0_TVALID_temp;
    wire src_axi0_TDATA_full;
    wire src_axi0_TDATA_empty;
    reg src_axi0_TDATA_write_en;
    reg [24 - 1:0] src_axi0_TDATA_write_data;
    reg src_axi0_TDATA_read_en;
    wire [24 - 1:0] src_axi0_TDATA_read_data;
    
    fifo #(1228800, 24) fifo_src_axi0_TDATA (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(src_axi0_TDATA_write_en),
        .write_data(src_axi0_TDATA_write_data),
        .read_clock(clk),
        .read_en(src_axi0_TDATA_read_en),
        .read_data(src_axi0_TDATA_read_data),
        .full(src_axi0_TDATA_full),
        .empty(src_axi0_TDATA_empty));
    
    always @ (*) begin
        src_axi0_TDATA_write_en <= TRAN_src_axi0_TVALID;
        src_axi0_TDATA_write_data <= TRAN_src_axi0_TDATA;
        src_axi0_TDATA_read_en <= 0;
    end
    wire src_axi0_TKEEP_full;
    wire src_axi0_TKEEP_empty;
    reg src_axi0_TKEEP_write_en;
    reg [3 - 1:0] src_axi0_TKEEP_write_data;
    reg src_axi0_TKEEP_read_en;
    wire [3 - 1:0] src_axi0_TKEEP_read_data;
    
    fifo #(1228800, 3) fifo_src_axi0_TKEEP (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(src_axi0_TKEEP_write_en),
        .write_data(src_axi0_TKEEP_write_data),
        .read_clock(clk),
        .read_en(src_axi0_TKEEP_read_en),
        .read_data(src_axi0_TKEEP_read_data),
        .full(src_axi0_TKEEP_full),
        .empty(src_axi0_TKEEP_empty));
    
    always @ (*) begin
        src_axi0_TKEEP_write_en <= TRAN_src_axi0_TVALID;
        src_axi0_TKEEP_write_data <= TRAN_src_axi0_TKEEP;
        src_axi0_TKEEP_read_en <= 0;
    end
    wire src_axi0_TSTRB_full;
    wire src_axi0_TSTRB_empty;
    reg src_axi0_TSTRB_write_en;
    reg [3 - 1:0] src_axi0_TSTRB_write_data;
    reg src_axi0_TSTRB_read_en;
    wire [3 - 1:0] src_axi0_TSTRB_read_data;
    
    fifo #(1228800, 3) fifo_src_axi0_TSTRB (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(src_axi0_TSTRB_write_en),
        .write_data(src_axi0_TSTRB_write_data),
        .read_clock(clk),
        .read_en(src_axi0_TSTRB_read_en),
        .read_data(src_axi0_TSTRB_read_data),
        .full(src_axi0_TSTRB_full),
        .empty(src_axi0_TSTRB_empty));
    
    always @ (*) begin
        src_axi0_TSTRB_write_en <= TRAN_src_axi0_TVALID;
        src_axi0_TSTRB_write_data <= TRAN_src_axi0_TSTRB;
        src_axi0_TSTRB_read_en <= 0;
    end
    wire src_axi0_TUSER_full;
    wire src_axi0_TUSER_empty;
    reg src_axi0_TUSER_write_en;
    reg [1 - 1:0] src_axi0_TUSER_write_data;
    reg src_axi0_TUSER_read_en;
    wire [1 - 1:0] src_axi0_TUSER_read_data;
    
    fifo #(1228800, 1) fifo_src_axi0_TUSER (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(src_axi0_TUSER_write_en),
        .write_data(src_axi0_TUSER_write_data),
        .read_clock(clk),
        .read_en(src_axi0_TUSER_read_en),
        .read_data(src_axi0_TUSER_read_data),
        .full(src_axi0_TUSER_full),
        .empty(src_axi0_TUSER_empty));
    
    always @ (*) begin
        src_axi0_TUSER_write_en <= TRAN_src_axi0_TVALID;
        src_axi0_TUSER_write_data <= TRAN_src_axi0_TUSER;
        src_axi0_TUSER_read_en <= 0;
    end
    wire src_axi0_TLAST_full;
    wire src_axi0_TLAST_empty;
    reg src_axi0_TLAST_write_en;
    reg [1 - 1:0] src_axi0_TLAST_write_data;
    reg src_axi0_TLAST_read_en;
    wire [1 - 1:0] src_axi0_TLAST_read_data;
    
    fifo #(1228800, 1) fifo_src_axi0_TLAST (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(src_axi0_TLAST_write_en),
        .write_data(src_axi0_TLAST_write_data),
        .read_clock(clk),
        .read_en(src_axi0_TLAST_read_en),
        .read_data(src_axi0_TLAST_read_data),
        .full(src_axi0_TLAST_full),
        .empty(src_axi0_TLAST_empty));
    
    always @ (*) begin
        src_axi0_TLAST_write_en <= TRAN_src_axi0_TVALID;
        src_axi0_TLAST_write_data <= TRAN_src_axi0_TLAST;
        src_axi0_TLAST_read_en <= 0;
    end
    wire src_axi0_TID_full;
    wire src_axi0_TID_empty;
    reg src_axi0_TID_write_en;
    reg [1 - 1:0] src_axi0_TID_write_data;
    reg src_axi0_TID_read_en;
    wire [1 - 1:0] src_axi0_TID_read_data;
    
    fifo #(1228800, 1) fifo_src_axi0_TID (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(src_axi0_TID_write_en),
        .write_data(src_axi0_TID_write_data),
        .read_clock(clk),
        .read_en(src_axi0_TID_read_en),
        .read_data(src_axi0_TID_read_data),
        .full(src_axi0_TID_full),
        .empty(src_axi0_TID_empty));
    
    always @ (*) begin
        src_axi0_TID_write_en <= TRAN_src_axi0_TVALID;
        src_axi0_TID_write_data <= TRAN_src_axi0_TID;
        src_axi0_TID_read_en <= 0;
    end
    wire src_axi0_TDEST_full;
    wire src_axi0_TDEST_empty;
    reg src_axi0_TDEST_write_en;
    reg [1 - 1:0] src_axi0_TDEST_write_data;
    reg src_axi0_TDEST_read_en;
    wire [1 - 1:0] src_axi0_TDEST_read_data;
    
    fifo #(1228800, 1) fifo_src_axi0_TDEST (
        .reset(1'b0),
        .write_clock(clk),
        .write_en(src_axi0_TDEST_write_en),
        .write_data(src_axi0_TDEST_write_data),
        .read_clock(clk),
        .read_en(src_axi0_TDEST_read_en),
        .read_data(src_axi0_TDEST_read_data),
        .full(src_axi0_TDEST_full),
        .empty(src_axi0_TDEST_empty));
    
    always @ (*) begin
        src_axi0_TDEST_write_en <= TRAN_src_axi0_TVALID;
        src_axi0_TDEST_write_data <= TRAN_src_axi0_TDEST;
        src_axi0_TDEST_read_en <= 0;
    end
    assign TRAN_src_axi0_TVALID = TRAN_src_axi0_TVALID_temp;

    
    assign TRAN_src_axi0_TREADY = ~(src_axi0_TDATA_full || src_axi0_TKEEP_full || src_axi0_TSTRB_full || src_axi0_TUSER_full || src_axi0_TLAST_full || src_axi0_TID_full || src_axi0_TDEST_full);
    
    function is_blank_char(input [7:0] in_char);
        if (in_char == " " || in_char == "\011" || in_char == "\012" || in_char == "\015") begin
            is_blank_char = 1;
        end else begin
            is_blank_char = 0;
        end
    endfunction
    
    function [143:0] read_token(input integer fp);
        integer ret;
        begin
            read_token = "";
                    ret = 0;
                    ret = $fscanf(fp,"%s",read_token);
        end
    endfunction
    
    function [143:0] rm_0x(input [143:0] token);
        reg [143:0] token_tmp;
        integer i;
        begin
            token_tmp = "";
            for (i = 0; token[15:0] != "0x"; token = token >> 8) begin
                token_tmp = (token[7:0] << (8 * i)) | token_tmp;
                i = i + 1;
            end
            rm_0x = token_tmp;
        end
    endfunction
    
    reg done_1;
    
    always @ (posedge clk or reset) begin
        if (~reset) begin
            done_1 <= 0;
        end else begin
            done_1 <= done;
        end
    end
    
    reg [31:0] transaction_save_src_axi0_TDATA;
    
    assign transaction = transaction_save_src_axi0_TDATA;
    
    initial begin : AXI_stream_receiver_src_axi0_TDATA
        integer fp;
        reg [24 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_src_axi0_TDATA = 0;
        fifo_src_axi0_TDATA.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_src_axi0_TDATA, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_src_axi0_TDATA);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_src_axi0_TDATA);
                while (~fifo_src_axi0_TDATA.empty) begin
                    fifo_src_axi0_TDATA.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_src_axi0_TDATA = transaction_save_src_axi0_TDATA + 1;
                fifo_src_axi0_TDATA.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_src_axi0_TKEEP;
    
    initial begin : AXI_stream_receiver_src_axi0_TKEEP
        integer fp;
        reg [3 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_src_axi0_TKEEP = 0;
        fifo_src_axi0_TKEEP.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_src_axi0_TKEEP, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_src_axi0_TKEEP);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_src_axi0_TKEEP);
                while (~fifo_src_axi0_TKEEP.empty) begin
                    fifo_src_axi0_TKEEP.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_src_axi0_TKEEP = transaction_save_src_axi0_TKEEP + 1;
                fifo_src_axi0_TKEEP.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_src_axi0_TSTRB;
    
    initial begin : AXI_stream_receiver_src_axi0_TSTRB
        integer fp;
        reg [3 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_src_axi0_TSTRB = 0;
        fifo_src_axi0_TSTRB.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_src_axi0_TSTRB, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_src_axi0_TSTRB);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_src_axi0_TSTRB);
                while (~fifo_src_axi0_TSTRB.empty) begin
                    fifo_src_axi0_TSTRB.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_src_axi0_TSTRB = transaction_save_src_axi0_TSTRB + 1;
                fifo_src_axi0_TSTRB.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_src_axi0_TUSER;
    
    initial begin : AXI_stream_receiver_src_axi0_TUSER
        integer fp;
        reg [1 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_src_axi0_TUSER = 0;
        fifo_src_axi0_TUSER.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_src_axi0_TUSER, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_src_axi0_TUSER);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_src_axi0_TUSER);
                while (~fifo_src_axi0_TUSER.empty) begin
                    fifo_src_axi0_TUSER.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_src_axi0_TUSER = transaction_save_src_axi0_TUSER + 1;
                fifo_src_axi0_TUSER.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_src_axi0_TLAST;
    
    initial begin : AXI_stream_receiver_src_axi0_TLAST
        integer fp;
        reg [1 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_src_axi0_TLAST = 0;
        fifo_src_axi0_TLAST.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_src_axi0_TLAST, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_src_axi0_TLAST);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_src_axi0_TLAST);
                while (~fifo_src_axi0_TLAST.empty) begin
                    fifo_src_axi0_TLAST.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_src_axi0_TLAST = transaction_save_src_axi0_TLAST + 1;
                fifo_src_axi0_TLAST.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_src_axi0_TID;
    
    initial begin : AXI_stream_receiver_src_axi0_TID
        integer fp;
        reg [1 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_src_axi0_TID = 0;
        fifo_src_axi0_TID.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_src_axi0_TID, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_src_axi0_TID);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_src_axi0_TID);
                while (~fifo_src_axi0_TID.empty) begin
                    fifo_src_axi0_TID.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_src_axi0_TID = transaction_save_src_axi0_TID + 1;
                fifo_src_axi0_TID.clear();
                $fclose(fp);
            end
        end
    end
    
    reg [31:0] transaction_save_src_axi0_TDEST;
    
    initial begin : AXI_stream_receiver_src_axi0_TDEST
        integer fp;
        reg [1 - 1:0] data;
        reg [8 * 5:1] str;
        
        transaction_save_src_axi0_TDEST = 0;
        fifo_src_axi0_TDEST.clear();
        wait (reset === 1);
        forever begin
            @ (negedge clk);
            if (done_1 == 1) begin
                fp = $fopen(`TV_OUT_src_axi0_TDEST, "a");
                if (fp == 0) begin // Failed to open file
                    $display("ERROR: Failed to open file \"%s\"!", `TV_OUT_src_axi0_TDEST);
                    $finish;
                end
                $fdisplay(fp, "[[transaction]] %d", transaction_save_src_axi0_TDEST);
                while (~fifo_src_axi0_TDEST.empty) begin
                    fifo_src_axi0_TDEST.pop(data);
                    $fdisplay(fp, "0x%x", data);
                end
                $fdisplay(fp, "[[/transaction]]");
                transaction_save_src_axi0_TDEST = transaction_save_src_axi0_TDEST + 1;
                fifo_src_axi0_TDEST.clear();
                $fclose(fp);
            end
        end
    end

endmodule
