// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XTEST_PATTERN1_H
#define XTEST_PATTERN1_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xtest_pattern1_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XTest_pattern1_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XTest_pattern1;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XTest_pattern1_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XTest_pattern1_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XTest_pattern1_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XTest_pattern1_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XTest_pattern1_Initialize(XTest_pattern1 *InstancePtr, u16 DeviceId);
XTest_pattern1_Config* XTest_pattern1_LookupConfig(u16 DeviceId);
int XTest_pattern1_CfgInitialize(XTest_pattern1 *InstancePtr, XTest_pattern1_Config *ConfigPtr);
#else
int XTest_pattern1_Initialize(XTest_pattern1 *InstancePtr, const char* InstanceName);
int XTest_pattern1_Release(XTest_pattern1 *InstancePtr);
#endif

void XTest_pattern1_Start(XTest_pattern1 *InstancePtr);
u32 XTest_pattern1_IsDone(XTest_pattern1 *InstancePtr);
u32 XTest_pattern1_IsIdle(XTest_pattern1 *InstancePtr);
u32 XTest_pattern1_IsReady(XTest_pattern1 *InstancePtr);
void XTest_pattern1_EnableAutoRestart(XTest_pattern1 *InstancePtr);
void XTest_pattern1_DisableAutoRestart(XTest_pattern1 *InstancePtr);


void XTest_pattern1_InterruptGlobalEnable(XTest_pattern1 *InstancePtr);
void XTest_pattern1_InterruptGlobalDisable(XTest_pattern1 *InstancePtr);
void XTest_pattern1_InterruptEnable(XTest_pattern1 *InstancePtr, u32 Mask);
void XTest_pattern1_InterruptDisable(XTest_pattern1 *InstancePtr, u32 Mask);
void XTest_pattern1_InterruptClear(XTest_pattern1 *InstancePtr, u32 Mask);
u32 XTest_pattern1_InterruptGetEnabled(XTest_pattern1 *InstancePtr);
u32 XTest_pattern1_InterruptGetStatus(XTest_pattern1 *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
